name: Workflow pour les tags vX_Y_Z

on:
  push:
    tags:
      - 'v[0-9]+_[0-9]+_[0-9]+'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Vérifier la branche
        run: |
          if [ "$GITHUB_REF" != "refs/heads/main" ]; then
            echo "Ce workflow ne s'exécute que sur la branche principale."
            exit 1
          fi
      - name: Vérifier le format du tag
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+_[0-9]+_[0-9]+$ ]]; then
            echo "Le format du tag n'est pas valide. Utilisez vX_Y_Z où X, Y et Z sont des entiers."
            exit 1
          fi
